experiment_name  : "RoBERTaBase kaggle check"
bucket_name      : "kaggleops-bucket"
git_uri          : "https://github.com/yuooka/kaggleops-tutorial.git"



MODEL_TYPE       : "RoBERTaBaseSquad2"
SEED             : 100
TORCH_SEED       : 101
FOLD             : 5
FOLD_NUM         : 0
TRAIN_BATCH_SIZE : 24
VALID_BATCH_SIZE : 24
MAX_LEN          : 160
DROPOUT          : 0.0
WEIGHT           : False
SCHEDULER        : "get_linear_schedule_with_warmup"
BUCKET           : True
CAT_HIDDEN       : [-2]
QA_TASK          : True
LOSS_TYPE        : "CROSS_ENTROPY"
SWA              : True
LR               : 0.00005
WEIGHT_DECAY     : 0.001
WARMUP           : 0.01
EPOCHS           : 2
PRE_PROCESS      : True